POST http://localhost:5000/admin/auth/register
Content-Type: application/json

{
    "username" : "dotu123",
    "password" : "dothanhtu"
}

###

POST http://localhost:5000/admin/auth/login
Content-Type: application/json

{
    "username" : "dotu",
    "password" : "dothanhtu"
}

###

POST http://localhost:5000/admin/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWE0N2JkNWFkMTU1ZjZhNGFhMTk3MzEiLCJpYXQiOjE2MzgxODI3OTF9.xMyJeU2KSB3v-Et3T_Mbr_w_TpRkRTt06KT3r3F6S10

{
    "title" : "React",
    "description" : "react",
    "text" : "Chó vàng Việt Nam là giống chó vàng đặc biệt xịn chỉ xuất hiện duy nhất ở Việt Nam",
    "status" : "Chó"
}

### 

GET http://localhost:5000/admin/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWE0N2JkNWFkMTU1ZjZhNGFhMTk3MzEiLCJpYXQiOjE2MzgxODI3OTF9.xMyJeU2KSB3v-Et3T_Mbr_w_TpRkRTt06KT3r3F6S10

###

PUT http://localhost:5000/admin/posts/61a492a8d39279ff209fad17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWE0N2JkNWFkMTU1ZjZhNGFhMTk3MzEiLCJpYXQiOjE2MzgxNzUzODd9.iyxLRBUkleFK_cMNL56VxrzbVdRCvv-BlHtdmeDdHdo

{
    "title": "Vueeeeeee",
    "description": "VUEEE",
    "url": "vue.org",
    "status": "LEARNING"
}

###
DELETE  http://localhost:5000/admin/posts/61a492a8d39279ff209fad17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWE0N2JkNWFkMTU1ZjZhNGFhMTk3MzEiLCJpYXQiOjE2MzgxNzUzODd9.iyxLRBUkleFK_cMNL56VxrzbVdRCvv-BlHtdmeDdHdo

###############################
GET http://localhost:5000/admin/auth/Account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWE0N2JkNWFkMTU1ZjZhNGFhMTk3MzEiLCJpYXQiOjE2MzgxODI3OTF9.xMyJeU2KSB3v-Et3T_Mbr_w_TpRkRTt06KT3r3F6S10

################################
PUT http://localhost:5000/admin/auth/61a47bd5ad155f6a4aa19731
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWE0N2JkNWFkMTU1ZjZhNGFhMTk3MzEiLCJpYXQiOjE2MzgyNjYzNzF9.s-ddrip2IRPQmcu7SL5CfGlPkPp9pHOpxxqkAeV5rWw

{
    "status": "Khóa"
}

################################
GET http://localhost:5000/admin/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWI3NTAwYTgxNjYxNWE3OGVmMDA2ZDYiLCJpYXQiOjE2Mzk0MTIxNDZ9.0_93r6uqfufLiHrXTWrSDAbr8UrO_ExlNDFvqxWHZxU

################################
POST http://localhost:5000/admin/product
Content-Type: application/json

{
    "nameProduct" : "Cho vang",
    "cateName" : "Cho",
    "price" : "3000000",
    "description" : "cho nay la cho dac biet hang viet nam chat luong cao",
    "img" : "https://cdn.tgdd.vn/Products/Images/42/220833/samsung-galaxy-s21-tim-600x600.jpg",
    "rating" : "5",
    "amount" : "5",
    "status" : "Hoạt động"
} 


